#!/bin/bash

# A non-installed actool can be used, for example:
# ACTOOL=../../appc/spec/bin/actool
ACTOOL=${ACTOOL:-actool}

IMAGEDIR=${IMAGEDIR:-bin/image-aci}

VERSION=$1

if [ ! -x "$ACTOOL" ] ; then
    echo "actool ($ACTOOL) is not executable"
    exit 1
fi

if [ ! -x bin/aciexamples ] ; then
    echo "bin/aciexamples not found. Is it compiled?"
    exit 1
fi

mkdir -p $IMAGEDIR/rootfs
if [ ! -d $IMAGEDIR/rootfs -o ! -x $IMAGEDIR/rootfs ]; then
    echo "$IMAGEDIR/rootfs is not a writeable directory"
    exit 1
fi

cp aciexamples          $IMAGEDIR/rootfs/
cp README.md            $IMAGEDIR/rootfs/
mkdir -p $IMAGEDIR/rootfs/mnt/vol{1,2,3,4,5}

cp manifest $IMAGEDIR/manifest

$ACTOOL build -overwrite=true $IMAGEDIR bin/aciexamples-1-linux-amd64.aci
